# Site settings
title: Mário Ribeiro - Developer based in London
email: mail@marioribeiro.com
description: > # Mario Ribeiro's homepage. I'm a developer based in London
baseurl: ""
url: "http://marioribeiro.com"

# Build settings
markdown: kramdown
exclude: [node_modules, Gemfile, Gemfile.lock, package.json, gulpfile.js]
gems: [octopress-autoprefixer, jemoji, jekyll-sitemap]
