# Site settings
title: Mário Ribeiro - Product Manager & UI / UX Designer
email: mail@marioribeiro.com
description: > # Mario Ribeiro homepage. I'm a product manager, designer and developer based in London.
baseurl: ""
url: "http://www.marioribeiro.com"

# Build settings
markdown: kramdown
exclude: [node_modules, Gemfile, Gemfile.lock, package.json, gulpfile.js]
gems: [octopress-autoprefixer, jemoji]
